server:
  port: 8080
spring:
  application:
    name: mall-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true  #使用小写service-id
logging:
  level:
    org.springframework.cloud.gateway: debug

