eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
server:
  port: 8020
spring:
  application:
    name: mall-front
  datasource:
    url: jdbc:mysql://localhost:3306/mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 106257
    druid:
      initial-size: 5 #连接池初始化大小
      min-idle: 10 #最小空闲连接数
      max-active: 20 #最大连接数
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #不统计这些请求数据
      stat-view-servlet: #访问监控网页的登录用户名和密码
        login-username: druid
        login-password: druid
  redis:
    host: localhost
    database: 0
    port: 6379
    password:
    lettuce:
      pool:
        max-active: 8  # 连接池最大连接数
        max-idle: 8  # 连接池最大空闲连接数
        min-idle: 0  # 连接池最小空闲连接数
        max-wait: -1ms  # 连接池最大阻塞等待时间，负值表示没有限制
    timeout: 3000ms
    #自定义 redis key
    key:
      perfix:
        autoCode: "front:authCode"
      expire:
        authCode: 120
      category: "home:category" #分类信息
      homeAdvertise: "home:advertise" #轮播图信息
      flashPromotion: "home:flash" #闪购信息
      homeProduct: "home:product" #首页推荐商品
    expireTime: 86400 # 60*60*24一天过期
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
mybatis:
  mapper-locations:
    - classpath:dao/*.xml
    - classpath*:com/**/mapper/*.xml
jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret: mall-front-secret #JWT加解密使用的密钥
  expiration: 604800 #JWT的超期限时间(60*60*24)
  tokenHead: Bearer #JWT负载中拿到开头
secure:
  ignored:
    urls: #安全路径白名单
      - /swagger-ui.html
      - /swagger-resources/**
      - /swagger/**
      - /**/v2/api-docs
      - /**/*.js
      - /**/*.css
      - /**/*.png
      - /**/*.ico
      - /webjars/springfox-swagger-ui/**
      - /druid/**
      - /actuator/**
      - /sso/login
      - /home/**
      - /redis/**
      - /esProduct/**
      - /product/**
threadPool:
  #核心线程数
  core-pool-size: 5
  #最大线程数
  max-pool-size: 5
  #配置队列大小
  queue-size: 9999
  #线程前缀
  thread-name-prefix: mall-front-service-
logging:
  level:
    com.wang.mall.mapper: debug
    com.wang.mall.front.dao: debug
